name: Idea/suggestion
description: Suggest a new tip/info to add on the website, or any other type of idea for dsd.mael.im
title: "[Idea]: "
labels: ["idea"]
assignees:
  -
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this idea suggestion form!
  - type: dropdown
    id: idea-type
    attributes:
      label: Idea type
      description: In what category below would you put your idea?
      multiple: false
      options:
        - New tip, information or question/answer
        - Improvement of the website in itself
        - Diversification of the website
        - None of the above
    validations:
        required: true
  - type: textarea
    id: idea-details
    attributes:
      label: Idea details
      description: Please tell us about your idea
      placeholder: What brilliant idea crossed your mind?
    validations:
      required: true
