name: Translation
description: Translate dsd.mael.im in a language it was not translated into yet
title: "[Translation]: "
labels: ["translation", "english"]
assignees:
body:
  - type: markdown
    attributes:
      value: |
        Thanks for considering translating the website to a new language. Please make sure you read the [Translating Guidelines](https://github.com/MaelImhof/dsd.mael.im/tree/main/TRANSLATIONS.md)
  - type: input
    id: language
    attributes:
      label: Language
      description: What language do you plan to translate the website into?
      placeholder: ex. german
    validations:
      required: true
  - type: input
    id: fork
    attributes:
      label: Fork
      description: If you are working on this translation in a forked repository, please provide the url of this repo
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Avoiding duplicates
      description: By submitting this issue, you acknowledge the fact that you checked that the website is not already being translated into the wanted language.
      options:
        - label: I checked for another on-going translation in this language and couldn't find one
          required: true